### ISSUE TITLE
FC is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#20]
* Your development environment (IntelliJ version, Java version, OS, ...)
Intellij March '20 Community Edition, Java 11, Windows 10 64-bit
* Relevant code, error message, stack trace
'FC' is not recognized as an internal or external command,
operable program or batch file.

Hello everybody, I get the above error message when trying to run the script to test my program(between level 4 and level 5). I did not make any changes to the script as it appears to me that the location of the file is correct. I have attached a screenshot of my file structure as it appears in Intellij, in the link below. Any help is appreciated. Thank you. 

https://drive.google.com/file/d/11NM1nVkkfjoNYxjgtpEkgSGA0tPgw4h2/view?usp=sharing

**Comment by SoonKeatNeo** [comment]
The FC command is actually similar to the Unix `diff` command that shows the differences between two files (in this case, the ACTUAL.TXT vs EXPECTED.TXT).

If you try to replace it with the full path of where the executable exists, does it work? (i.e. this is usually found in `C:\Windows\system32\fc.exe`)

If it does work, it may indicate a problem with PATH environment variables.

**Comment by damithc** [comment]
@fairyinabottle4 It might help to specify in what kind of terminal you were using. e.g., regular DOS prompt, PowerShell or a terminal in WSL

**Comment by fairyinabottle4** [comment]
@SoonKeatNeo Thank you, I replaced the FC command with the full path and it worked. What should I do to rectify the environment variable issue? (The other day I had some trouble with my Java version and I might have messed it up accidentally)

@damithc I'm using the terminal in Intellij. Now that I have managed to run the script, may I ask why the expected text is still the "Hello from Duke" instead of the chatbot response? I have attached a screenshot of my output below

https://drive.google.com/file/d/1K4X8LvO5M_RGMw_-3ZsshfwYpiKTKoFZ/view?usp=sharing

Thank you

**Comment by damithc** [comment]
> @damithc I'm using the terminal in Intellij. Now that I have managed to run the script, may I ask why the expected text is still the "Hello from Duke" instead of the chatbot response? I have attached a screenshot of my output below

Have you updated the EXPECTED.TXT with the expected chatbot response?

**Comment by w2vgd** [comment]
> @damithc I'm using the terminal in Intellij. Now that I have managed to run the script, may I ask why the expected text is still the "Hello from Duke" instead of the chatbot response? I have attached a screenshot of my output below


You are expected to update the _EXPECTED.txt_ yourself to match your own chatbot's functionality. The given "Hello from Duke" is just a template.

**Comment by SoonKeatNeo** [comment]
> Thank you, I replaced the FC command with the full path and it worked. What should I do to rectify the environment variable issue? (The other day I had some trouble with my Java version and I might have messed it up accidentally)

https://cromwell-intl.com/open-source/windows-path.html

Perhaps this would be helpful on Windows 10! Just ensure that the system32 directory is in the Path variable.

**Comment by danadi7** [comment]
@fairyinabottle4 You are right that it is an environmental variable issue that can be rectified. The most likely reason, as @SoonKeatNeo said above, is that somehow the `C:\Windows\System32` directory is somehow missing from the Path variable.

A quick Google search should lead you to this StackOverflow thread from 2013 with the same issue:
https://stackoverflow.com/questions/18570921/fc-is-not-recognized-as-an-internal-or-external-command-operable-program-or-b

Just add `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem` to your Path and it should be fixed.

**Comment by fairyinabottle4** [comment]
@danadi7 That solution didn't seem to work for me, I'm still getting FC is not a recognised command

**Comment by tohyuting** [comment]
Hi @fairyinabottle4, just to check: did you close and re-open the terminal in Intellij after adding system32 directory to your Path? This is usually needed in order for the terminal to re-import the environmental variables which you have just set. Otherwise, do you mind sharing a screenshot of the current environmental variables that you have added so far and other students can provide suggestions to help you solve the issue that you are currently facing :)

**Comment by fairyinabottle4** [comment]
@tohyuting I managed to solve the issue in the end by adding the '%' around the path variables, after taking at a friend's setup. Not sure why this is the case, but if anyone faces this issue, just take note that they are needed

**Comment by damithc** [comment]
> @tohyuting I managed to solve the issue in the end by adding the '%' around the path variables, after taking at a friend's setup. Not sure why this is the case, but if anyone faces this issue, just take note that they are needed

If you are referring to something like `%PATH%`, that means _the value of the `PATH` variable_
